services:
  mysql:
    image: mysql:8
    container_name: veterinario-mysql
    restart: always
    environment:
      MYSQL_DATABASE: appveterinario
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD}"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend: 
    build: ./backend/demo
    volumes:
      - ./imagens:/app/imagens
    container_name: veterinario-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env



  frontend:
    build: ./frontend
    container_name: veterinario-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    environment:
      VITE_API_URL: http://backend:8080


volumes:
  mysql_data:

