services:
  mysql:
    image: mysql:8
    container_name: veterinario-mysql
    restart: always
    environment:
      MYSQL_DATABASE: appveterinario
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-ppassword"]
      interval: 5s
      timeout: 5s
      retries: 10

  backend:
    build: .
    volumes:
      - ./imagens:/app/imagens
    container_name: veterinario-backend
    depends_on:
      mysql:
        condition: service_healthy
    ports:
      - "8080:8080"
    env_file:
      - .env


volumes:
  mysql_data:
